on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Deps
        run: yarn; npm install -g sass
      - name: Install php deps
        run: composer install
      - name: Compile Css
        run: sass scss/main.scss css/style.css
      - name: Deploy app
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.FTP_USERNAME }}
          server: ${{ secrets.FTP_SERVER }}
          local_path: './*'
          remote_path: '/httpdocs'
          sftp_only: true
          password: ${{ secrets.FTP_PASSWORD }}